### ISSUE TITLE
feat(LoginHeader): component

### ISSUE THREAD

**Issue by tomatozil** [42Box/front-end2.0#50]
헤더에 있는 알림 기능을 없애고 로그인/로그아웃 기능을 넣었습니다.
현재는 msw를 써서 가짜 응답을 기반으로, 
로그아웃 상태일 시 로그인 버튼을
로그인 상태일 시 로그아웃 버튼을 보여주려고 합니다.

따라서 하는 중인 것들.
- msw 라이브러리를 사용하여 mock worker(api 요청을 가로채서 가짜 응답을 주는 함수)을 구현
- 상태에 따라 버튼 다르게 보여주기

**Comment by Clearsu** [comment]
아주 기대됩니다!!!
